### PR TITLE
Add Support for Certificates, Identities and Keys

### PR DESCRIPTION
**Pull request by cfis**
Let me first say sorry for such a large pull request, but I needed read access to certificates, identities and keys which made this into a fairly large change set.  To do this, this commit it moves some functionality from Keychain::Item to Keychain::Base, then adds in new classes for certificates, identities and keys.  It then defines an ATTR_MAP hash per class since each class has different possible keys according to Appple's documentation.

These changes are backwards compatible and tests pass.  Note that creating and updates certificates, keys and identities is not currently supported.  That would require moving some more code from Keychain::Item down to the base class and generalzing Keychain::Scope#create.  That would be the next logical step, but for my purposes I only needed read access to certificates, identities and keys which these changes accomplish.

Let me know if you have any questions.

### CODE REVIEW

**Comment by cfis** [comment]
Sorry for the delay on this.  I added specs for the 3 new classes - certificates, keys and identities.  Hope they look ok - I use minitest all the time but never rspec.
I tried to base the test on certs that I think all OSX users have.

**Comment by fcheung** [comment]
Looks good - thanks. Will update gem etc next week - away at the moment

**Comment by fcheung** [comment]
Are you getting the same failure as travis locally? I could swear it said the specs were ok before I merged

**Comment by cfis** [comment]
Hmm, yeah is working here.  I wonder what osx version kSecAttrAccessControl was introduced.  What version of osx is travis running on?

**Comment by fcheung** [comment]
Ah, new in Yosemite ( https://developer.apple.com/library/mac/documentation/General/Reference/APIDiffsMacOSX10_10SeedDiff/frameworks/Security.html ) and travis docs say they run on 10.9.5. Perhaps you could just rescue the attaching of that constant? Not sure what best practise is here

**Comment by cfis** [comment]
That seems like a good idea...other approach would be put an if statement in that checks the osx version.  But I think rescue is good enough...

**Comment by cfis** [comment]
Thanks for taking care of this - I was going to do it this weekend but got sidetracked!

**Comment by legal90** [comment]
@cfis Could you please give an example - how to add new certificate/key to the keychain? It is missed in Readme?

**Comment by cfis** [comment]
Ah - the code in this pull request adds support for querying keys and certificates, but not for creating them.  I haven't looked at the creation apis - hopefully it would not be too hard for someone to add support for them (we just use the keychain app on osx so don't need that ability).

**Pull request merged**
